version: '2.1'

services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16685:16685"
      - "16686:16686"
      - "14268"
      - "14250"  

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"
      - "9411"   # Zipkin receiver

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin  
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080      